// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TomSelectController from "./tom_select_controller"
application.register("tom_select", TomSelectController)

import DarkLight from "./dark_light_controller"
application.register("dark-light", DarkLight)
import Flash from "./flash_controller"
application.register("flash", Flash)
import Sidebar from "./sidebar_controller"
application.register("sidebar", Sidebar)
